### ISSUE TITLE
Issue I am Unable used Generate Token api

### ISSUE THREAD

**Issue by javagovindsharma** [nianton/PowerBI-Client-Java#4]
Exception in thread "main" java.lang.RuntimeException: Authentication undefined: defaultAuth
	at com.microsoft.powerbi.ApiClient.updateParamsForAuth(ApiClient.java:1019)
	at com.microsoft.powerbi.ApiClient.buildRequest(ApiClient.java:895)
	at com.microsoft.powerbi.ApiClient.buildCall(ApiClient.java:874)
	at com.microsoft.powerbi.api.DashboardsApi.addDashboardCall(DashboardsApi.java:96)
	at com.microsoft.powerbi.api.DashboardsApi.addDashboardValidateBeforeCall(DashboardsApi.java:108)
	at com.microsoft.powerbi.api.DashboardsApi.addDashboardWithHttpInfo(DashboardsApi.java:133)
	at com.microsoft.powerbi.api.DashboardsApi.addDashboard(DashboardsApi.java:121)
	at powerBITest.powerbi_client.App.main(App.java:14)

**Comment by javagovindsharma** [comment]
import com.microsoft.powerbi.ApiException;
import com.microsoft.powerbi.api.DashboardsApi;
import com.microsoft.powerbi.models.AddDashboardRequest;
import com.microsoft.powerbi.models.Dashboard;

public class App {
	public static void main(String[] args) {
		DashboardsApi apiInstance = new DashboardsApi();
        AddDashboardRequest requestParameters = new AddDashboardRequest(); 
        try {
            Dashboard result = apiInstance.addDashboard(requestParameters);
            System.out.println(result);
        } catch (ApiException e) {
            System.err.println("Exception when calling DashboardsApi#addDashboard");
            e.printStackTrace();
        }
		
	}
}
